var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/pulse/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0-t.uk6._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ul73e7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0_3d5ui.js")
R.c("server/chunks/ssr/[root-of-the-server]__0yf_0wx._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09z7o2x._.js")
R.c("server/chunks/ssr/app_layout_tsx_13yf0ls._.js")
R.c("server/chunks/ssr/_0bn.7yp._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0ee1czk._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_pulse_page_actions_0_yp94-.js")
R.m(65547)
module.exports=R.m(65547).exports
