// MonoKromatik Publisher Agent
// Merges new articles into data/articles.json with deduplication, then commits + pushes.
// Vercel webhook auto-deploys. The git commit IS the publishing event.

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { execSync } from 'child_process';
import { join } from 'path';
import type { GeneratedArticle } from './generate-article';

const ARTICLES_PATH = join(process.cwd(), 'data', 'articles.json');

interface StoredArticle extends GeneratedArticle {}

/**
 * Load existing articles
 */
function loadExisting(): StoredArticle[] {
  if (!existsSync(ARTICLES_PATH)) return [];
  return JSON.parse(readFileSync(ARTICLES_PATH, 'utf-8'));
}

/**
 * Title similarity check — basic Jaccard on word sets.
 * Catches "Tyla drops album" vs "Tyla's new album drops" without needing a vector DB.
 */
function isDuplicate(a: string, b: string): boolean {
  const norm = (s: string) =>
    new Set(
      s
        .toLowerCase()
        .replace(/[^a-z0-9\s]/g, '')
        .split(/\s+/)
        .filter((w) => w.length > 3)
    );
  const A = norm(a);
  const B = norm(b);
  if (A.size === 0 || B.size === 0) return false;
  const inter = new Set([...A].filter((x) => B.has(x))).size;
  const union = new Set([...A, ...B]).size;
  return inter / union > 0.6; // 60% overlap = duplicate
}

/**
 * Merge new articles into the store, skipping duplicates by slug AND by title similarity
 */
export function mergeArticles(newOnes: StoredArticle[]): {
  merged: number;
  skipped: number;
  total: number;
} {
  const existing = loadExisting();
  const existingSlugs = new Set(existing.map((a) => a.slug));

  let merged = 0;
  let skipped = 0;

  for (const article of newOnes) {
    if (existingSlugs.has(article.slug)) {
      skipped++;
      continue;
    }
    const dup = existing.find((e) => isDuplicate(e.title, article.title));
    if (dup) {
      console.log(
        `   ⚠️  Skipping near-duplicate: "${article.title}" ≈ "${dup.title}"`
      );
      skipped++;
      continue;
    }
    existing.unshift(article); // newest first
    existingSlugs.add(article.slug);
    merged++;
  }

  // Sort newest first
  existing.sort(
    (a, b) =>
      new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime()
  );

  writeFileSync(ARTICLES_PATH, JSON.stringify(existing, null, 2));

  return { merged, skipped, total: existing.length };
}

/**
 * Commit + push the changes. Vercel picks up the push and rebuilds production.
 */
export function commitAndPush(commitMessage: string): boolean {
  try {
    // Are we in a clean working tree? (besides articles.json)
    execSync('git add data/articles.json', { stdio: 'inherit' });

    const status = execSync('git status --porcelain data/articles.json', {
      encoding: 'utf-8',
    });
    if (!status.trim()) {
      console.log('   ℹ️  No changes to commit (articles.json unchanged)');
      return false;
    }

    execSync(`git commit -m "${commitMessage.replace(/"/g, '\\"')}"`, {
      stdio: 'inherit',
    });
    execSync('git push origin main', { stdio: 'inherit' });
    console.log('   🚀 Pushed to GitHub. Vercel will deploy automatically.');
    return true;
  } catch (e) {
    console.error('   ❌ Git commit/push failed:', e instanceof Error ? e.message : e);
    return false;
  }
}

/**
 * Full publish: merge + commit + push
 */
export function publishArticles(articles: StoredArticle[], dryRun = false): {
  merged: number;
  skipped: number;
  total: number;
  pushed: boolean;
} {
  const result = mergeArticles(articles);
  console.log(
    `\n   📝 Merge: ${result.merged} new · ${result.skipped} skipped · ${result.total} total`
  );
  if (dryRun || result.merged === 0) {
    return { ...result, pushed: false };
  }
  const message = `feat(content): publish ${result.merged} new article${
    result.merged > 1 ? 's' : ''
  } via agent

${articles
  .slice(0, result.merged)
  .map((a) => `- ${a.title}`)
  .join('\n')}

🤖 Generated by MonoKromatik agents`;
  const pushed = commitAndPush(message);
  return { ...result, pushed };
}
